### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by abdrehman98** [twrackers/Calculus-library#4]
Is there any documentation for which Libraries i have to use 
Like there are multiple Libraries Available for Streaming.h

can you please specify?

**Comment by twrackers** [comment]
Sorry, I just found your comment from 11 months ago.  I haven't been in my GitHub for quite a while.  It's late right now, but I will try to get an answer to you tomorrow 2020/4/24.

**Comment by abdrehman98** [comment]
No problem @twrackers. I was working on the control systems program back then. I was trying to implement PID control on Arduino. But the issue was resolved.
